### ISSUE TITLE
sử dụng ntn :D

### ISSUE THREAD

**Issue by thaobn20** [truongwp/gallery-meta-box#1]
chèn vô sao bác

**Comment by truongwp** [comment]
Hi @thaobn20,
Bạn cần include file `gallery-meta-box.php`, hoặc nếu bạn sử dụng composer, chạy `composer require truongwp/gallery-meta-box="*"`.
Lưu ý, nó chỉ sử dụng được trong plugin

**Comment by truongwp** [comment]
@thaobn20 bạn cần thêm đoạn filter sau để nó hoạt động chỉ với san-pham

```php
function truongwp_filter_gallery_meta_box_post_types() {
    return 'san-pham';
}
add_filter( 'gallery_meta_box_post_types', 'truongwp_filter_gallery_meta_box_post_types' );
```
