### ISSUE TITLE
Show Gallery at front-end

### ISSUE THREAD

**Issue by NielsTieman** [truongwp/gallery-meta-box#2]
Hi,

We had contact this afternoon. I tried for hours, but no luck so far. I can see the menu in the back-end. But I can't seem to figure out a way to show the image(s) on the frontend. It has nothing to do with your plugin, but if you can help me out, I would be grateful. 

Thanks,
With regards,
Niels

**Comment by NielsTieman** [comment]
After hours of work I finally managed to get this working! Thanks for the pointers and de meta box.

**Comment by truongwp** [comment]
Thank you. I'll improve the documentation
