### ISSUE TITLE
Gallery appears and disappears

### ISSUE THREAD

**Issue by Phaidonas** [truongwp/gallery-meta-box#5]
Sorry for this, i tried your plug in, and now the gallery in post, on loading appears, and then disappears.

**Comment by truongwp** [comment]
Hi there,

Do you mean in the backend or frontend? Is there any error in browser console? Did you try to deactivate other plugins to test?

**Comment by Phaidonas** [comment]
In backend, i found it, she makes a strange effect on loading and after appears in the sidebar. Ok cool, Thank you.

**Comment by truongwp** [comment]
Hi,

Can you tell me which causes this?

**Comment by Phaidonas** [comment]
I dont know, when i load a post,at backend, it is like loading the gallery first and then loads the editor and the other content of the post. For milliseconds , like blink Now i used require, not include and loaded smoothly.

**Comment by truongwp** [comment]
Thank you. If it's ok now. I will close this issue.
